name: deploy

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    linters:
        name: Run prettier scanning
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install deps
              run: npm ci

            - name: Run prettier
              run: npm run prettier
    deploy:
        runs-on: ubuntu-latest
        needs:
            - linters
        steps:
            - name: Pull code
              uses: appleboy/ssh-action@master
              with:
                  host: 109.120.183.59
                  username: ubuntu
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: sudo bash -c "cd /home/ubuntu/front/MailJumper && git pull"
            - name: Build containers
              uses: appleboy/ssh-action@master
              with:
                  timeout: 30m
                  host: 109.120.183.59
                  username: ubuntu
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: |
                      sudo bash -c "
                        cd /home/ubuntu/front/MailJumper;
                        npm run build;
                        cp -rf ./dist/* /var/www/frontend/dist/;
                      "
